
services:
  web:
    container_name: web
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    #    env_file: .env
    volumes:
      - './frontend/app:/app/web'
      - './frontend/app/node_modules:/app/web/node_modules'
    ports:
      - '1000:1000'
    command: ["npm", "run", "start", "--", "--port", "1000"]
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/app/api'
      - './api/build/libs/api-0.0.1-SNAPSHOT.jar:/app/api/build/libs/api-0.0.1-SNAPSHOT.jar'
    ports:
      - 8080:8080
      - 1003:35729
    depends_on:
      - db
    #    command: ['java', '-jar', 'build/libs/api-0.0.1-SNAPSHOT.jar']
    command: ['./gradlew', 'bootRun']

  db:
    image: mysql:latest
    container_name: mysqlDatabase
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: default
    volumes:
      - my-db:/var/ lib/mysql
    ports:
      - '3306:3306'
volumes:
    my-db: