
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /src/web
    user: "1000:1000"
    volumes:
      - ./frontend:/src/web
    ports:
      - "8080:8080"
    command: [ "npm", "run", "serve" ]

  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/app/api'
      - './api/build/libs/api-0.0.1-SNAPSHOT.jar:/app/api/build/libs/api-0.0.1-SNAPSHOT.jar'
    ports:
      - 1001:8080
      - 1003:35729
    depends_on:
      - db
    #    command: ['java', '-jar', 'build/libs/api-0.0.1-SNAPSHOT.jar']
    command: ['./gradlew', 'bootRun']

  db:
    image: mysql:latest
    container_name: mysqlDatabase
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: default
    volumes:
      - my-db:/var/ lib/mysql
    ports:
      - '3309:3306'
volumes:
    my-db: